/// App commands callable from the webview. Declaring them makes tauri-build
/// generate `allow-<command>` permissions (in `permissions/autogenerated/`)
/// and makes the runtime check app commands against capabilities, so only
/// windows granted a command can invoke it.
///
/// Adding a command: add it to `generate_handler!` in `src/main.rs`, list it
/// here, and grant `allow-<command-with-dashes>` in `capabilities/settings.json`.
const COMMANDS: &[&str] = &[
    "get_settings",
    "save_settings",
    "list_models",
    "download_model",
    "delete_model",
    "get_autostart",
    "set_autostart",
    "start_session_recording",
    "stop_session_recording",
    "list_sessions",
    "delete_session",
    "get_session_transcript",
    "transcribe_session",
    "take_startup_error",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
